### ISSUE TITLE
CacheUtil.clear(key); 这个好象不起作用。。

### ISSUE THREAD

**Issue by live17909** [ronghao/CacheManage#4]
CacheUtil.clear(key); 这个好象不起作用。。

**Comment by live17909** [comment]
![image](https://user-images.githubusercontent.com/5187944/51652222-d8efea00-1fc9-11e9-9f30-27717240462f.png)
删除了，还是有很多文件在那里。

**Comment by ronghao** [comment]
确认为bug，感谢 @live17909 。请更新到1.3.1测试

**Comment by live17909** [comment]
已经ok。谢谢。
