### ISSUE TITLE
After the application freezes, there is no cache in the page where the application freezes

### ISSUE THREAD

**Issue by TikTak123** [ronghao/CacheManage#5]
Today, with the help of SwipeRefresh, I wanted to update the data in my application and my application hung. After that I manually closed it. After I restarted the application, but the page where I was updating the data there was no cache. After that, we started trying to reproduce this error. If we did SwipeRefresh many times without stopping, then at some point the application freezed and after that, as we re-enter it, the cache was not in the page where the application freezed. I can throw off the video as an error is reproduced.

**Comment by TikTak123** [comment]
Here is my Application class
@Override
public void onCreate() {
        super.onCreate();
	CacheUtilConfig cc = CacheUtilConfig.builder(this)
                .allowMemoryCache(true) // Allow storage to memory
                .allowEncrypt(false)
                .build();
        CacheUtil.init(cc);
}

**Comment by ronghao** [comment]
@TikTak123 
1、保存数据时，检查是否开启了文件读写权限？
2、在低频率保存数据时，是否能保存成功？

**Comment by TikTak123** [comment]
1. I have permission to read and write.
2. I don’t know. But I think this is not possible with this library. For experiment I tried to use other libraries.
https://github.com/kittinunf/Fuse
https://github.com/kernel0x/falcon
Both libraries do not show this error. For further I chose a library
https://github.com/kernel0x/falcon
Now, besides me, the testers will test it.

**Comment by ronghao** [comment]
1.你使用的哪一款手机？
2.clone一份代码，运行app，是否有问题？
3.是否方便提交一份关于你的代码
