### ISSUE TITLE
Application中初始化崩溃

### ISSUE THREAD

**Issue by q88qaz** [ronghao/CacheManage#7]
Process: com.zyhl.pudding, PID: 1318
    java.lang.RuntimeException: Unable to create application com.zyhl.pudding.MyApplication: android.database.sqlite.SQLiteException: Failed to change locale for db '/data/user/0/com.zyhl.pudding/databases/cachetest' to 'zh_CN'.
初始化崩溃

**Comment by ronghao** [comment]
是否有其他log，当前列出的错误日志为数据库问题，当前库采用文件读取，未涉及数据库操作。
请查看该网址：https://github.com/agrosner/DBFlow/issues/440
